services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: API
    build:
      context: .
      dockerfile: API/Dockerfile
      
  database:
    image: postgres:15
    container_name: DATABASE
    environment:
      - POSTGRES_DB=BlazorDemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432